name: Run CI
on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run prettier
        uses: creyD/prettier_action@v2.0
        with:
          prettier_options: "--no-semi --write *.js"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning the repository
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Run prettier
        uses: creyD/prettier_action@v2.0
        with:
          prettier_options: "--no-semi --write *.js"
          branch: ${{github.ref}}
      - run: yarn install
      - run: yarn build
      - run: yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true
