name: Run CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning the repository
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn test
        env:
          CI: true
